services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: salesdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d salesdb"]
      interval: 5s
      timeout: 5s
      retries: 10

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics --bootstrap-server localhost:9092 --list >/dev/null 2>&1"]
      interval: 10s
      timeout: 10s
      retries: 12

  jobmanager:
    image: flink:1.19.1-scala_2.12-java11
    command: jobmanager
    ports:
      - "8081:8081"
    environment:
      FLINK_PROPERTIES: |
        jobmanager.rpc.address: jobmanager
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_TOPIC: sales-json
      POSTGRES_URL: jdbc:postgresql://postgres:5432/salesdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    depends_on:
      - kafka
      - postgres

  taskmanager:
    image: flink:1.19.1-scala_2.12-java11
    command: taskmanager
    environment:
      FLINK_PROPERTIES: |
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2
    depends_on:
      - jobmanager

  producer:
    image: maven:3.9.9-eclipse-temurin-11
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_TOPIC: sales-json
      DATA_DIR: /app/исходные данные
    command: mvn -q -DskipTests compile exec:java -Dexec.mainClass=ru.bigdataflink.CsvToKafkaProducer
    depends_on:
      kafka:
        condition: service_healthy
